[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  VITE_API_URL = "https://lucemoon-crm-backend-2.onrender.com/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
